apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
kind: Pod
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 128Mi
          cpu: 1000m
  priorityClassName: high-priority

