Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # ===== VM 1 (Control Plane) =====
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"

    vm1.vm.network "public_network",
      bridge: "Intel(R) Dual Band Wireless-AC 8260 #2"

    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.cpus = 2
      vb.memory = 2000

      # Disable default NAT
      vb.customize ["modifyvm", :id, "--nic1", "none"]
    end
  end

  # ===== VM 2 (Worker) =====
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"

    vm2.vm.network "public_network",
      bridge: "Intel(R) Dual Band Wireless-AC 8260 #2"

    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
      vb.cpus = 1
      vb.memory = 1500

      # Disable default NAT
      vb.customize ["modifyvm", :id, "--nic1", "none"]
    end
  end
end
