Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # ===== VM 1 =====
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"

    # Private network
    vm1.vm.network "private_network", ip: "192.168.56.10"

    # Public network (bridge)
    vm1.vm.network "public_network", bridge: "Microsoft Wi-Fi Direct Virtual Adapter #8"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.cpus = 2
      vb.memory = 2000
    end
  end

  # ===== VM 2 =====
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"

    # Private network
    vm2.vm.network "private_network", ip: "192.168.56.11"
    vm2.vm.network "forwarded_port", guest: 30080, host: 30080
    vm2.vm.network "forwarded_port", guest: 30081, host: 30081
    # Public network (bridge)
    vm2.vm.network "public_network", bridge: "Microsoft Wi-Fi Direct Virtual Adapter #8"

    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
      vb.cpus = 1
      vb.memory = 1500
    end
  end
end

