---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
   metadata: 
    name: pod
    labels: 
     app: portfolio
   spec:
     containers:
      - name: portfolio
        image: victormungai/vprofile-image:db   
        ports:
          - containerPort: 80
