apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: adam
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWRENDQVR3Q0FRQXdEekVOTUFzR0ExVUVBd3dFWVdSaGJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQNCmdnRVBBRENDQVFvQ2dnRUJBT1YweVNOdnhpS2dIYk14Y1czR2xBcHJYai9jQUtmK3d3eitreWtOTFJObVZtSGgNCkFGenNhYnFGSk10b0FyRkxFdUQzUmM3aFExNUVVSlFEUzN3YjJtWWdjMjYwSkN4NHFlUXJPSm5uTEhwV2F0MUcNCnpaaVg5dko3ZXFQMEhXZ2N0YzhnTEQ3UC9jU2U2aHpWV2tvN2hnQlJEUlNtTTRQdnBhdThNcXJyN0FFRnV2Nm4NCis5TERmRlJlNkRLQjNFOXdrbytTWnlHd2tTQnFXcEl2RE1DaVlsWjlQUDc1d2tKSjByMDRaYW9uN0tUSURBMXYNCjFDMDg1dUxTOTMwUWExTmJ2WE5qVGNZT205ZXRCcDRnUEdtNkQ5czFFWmVrcWxCUm9MUHEwMUNGZWlqdktuVy8NCkNEc2FJZzM2a2lRS1RoSWhpWHdUYlUvYkp4WXhReXlXQkZ3STdXMENBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUINCkN3VUFBNElCQVFBcG9qdFhlTlFsQnliSWNDNWpPVjl6STVsbk9zaE16L0czWVRuaVFNdjZuRW1nbGlrV3lpNnoNCjczQjBmSVY3ay9vRmhiR3JxU2RlaEloQlloeWlCbUM2ZUUzY1g1K21ZSTlQektxaTc3N2FUUFhDT3U0Y3FFNTgNCnVuWEtyRlNrWnYra1BmQ3kyUUZyc1ppaDlQb09ERHo2SHNmSi9FczBHUXpWWVo4YnJyR25TL3R4aWpWU2duOTENCit2MjVjWEdRZkxKYmFvZ2hwbTdzOEdIYlp5dXNtVlFhSGtaRUhNV1UwWTBqdCtzM1hmVDdPc05OL3BxSktIUngNCkkwc0ZRcE80RzFJazdtVmFHcUJmc0Y5NVJleEJVdHVSREl1aDEwcld4WkFDNUQ5blZic0NnVGRwZG1VSFJNMXgNCkQxQWcvQm1Renl4MDIrU3l0cUl0ZU5ad09ub3l0OXl4DQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
    - digital signature
    - key encipherment
