---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: hp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hp
  template:
    metadata:
      name: hp
      labels: 
        app: hp
    spec:
      containers:
       - name: hp
         image: registry.k8s.io/e2e-test-images/goproxy:0.1
         ports:
          - containerPort: 8080
         args:
          - liveness
         livenessProbe:
           tcpSocket:
             port: 8080
           initialDelaySeconds: 15
           periodSeconds:  5
         readinessProbe:
           httpGet:
             path: /healthz
             port: 8080
           initialDelaySeconds: 5
           periodSeconds:  5
      


  


      affinity:
        nodeAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
             matchExpressions:
              - key: schedule
                operator: In
                values: 
                 - "true"


