apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis2
spec:
  containers:
  - image: redis
    name: redis2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
   nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 1
       preference:
         matchExpressions:
          - key: disktype
            operator: In
            values:
              - hdd
status: {}
