apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis3
spec:
  containers:
  - image: redis
    name: redis3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
   nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 1
       preference:
         matchExpressions:
          - key: disktype
            operator: Exists
status: {}
