Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Optional: increase boot timeout
  config.vm.boot_timeout = 600

  # ===== VM 1 (Control Plane) =====
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"

    # NAT adapter for SSH / Vagrant
    vm1.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true

    # Bridged network for Kubernetes cluster
    vm1.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260 #2", ip: "192.168.100.10"

    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.cpus = 2
      vb.memory = 2000
    end
  end

  # ===== VM 2 (Worker Node) =====
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"

    # NAT adapter for SSH / Vagrant
    vm2.vm.network "forwarded_port", guest: 22, host: 2223, auto_correct: true

    # Bridged network for Kubernetes cluster
    vm2.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8260 #2", ip: "192.168.100.11"

    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
      vb.cpus = 1
      vb.memory = 1500
    end
  end
end
