apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    env: dev-np
spec:
  selector:
      env: demo
  ports:
    - port: 30000 
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  type: NodePort
