apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
 ports:
    - port: 8090
      nodePort: 30001
      targetPort: portfolio-port
      protocol: TCP
 selector:
      app: portfolio
 type: NodePort
          
