kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP

    - containerPort: 30002
      hostPort: 30002
      protocol: TCP

    - containerPort: 30003
      hostPort: 30003
      protocol: TCP


- role: worker
- role: worker


