apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh","-c"]
      args: ["sleep 1h"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN","SYS_TIME"]
          drop: ["ALL"]
