---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replica
  labels:
    app: portfolio
spec:
  replicas: 5
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: victormungai/digital-portfolio

