apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://192.168.56.10:8200"
      path: "kv/prod"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: service-account-role
          serviceAccountRef:
            name: vault
            namespace: vault
