#After establishing a connection using the secret-store.yaml file this file creates a secret from our vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-api-key #This is the name of the secret that will  be created
  namespace: demo
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dev-api-credentials
  data:
  - secretKey: api-key
    remoteRef:
      key: "dev" # This is like  the folder where the key is tored or the environment
      property: "api-key" #This is the name of the actual key
