---
apiVersion: v1
kind: Pod
metadata: 
 name: pod1
 labels:
  app: secret-test
spec:
  containers:
    - name: container1
      image: nginx
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: secrets
              key: username

        - name: password
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password
   

